apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: wwj-corp-api
spec:
  type: openapi
  lifecycle: production
  owner: wwj-corp
  system: wwj-corp
  definition: |
    $yaml: 'https://github.com/wwj-member-application/tech-docs/blob/main/docs/api/private-access-api.v1.yaml'
